spring:
  application:
    name: irc-project

irc:
  ssl:
    keystore-path: classpath:keystone.p12
    # ???? ???? IRC_KEYSTORE_PASSWORD? ??? ?? ??, ??? 'password' ??
    # ??? ?? ???? ?????.
    keystore-password: ${IRC_KEYSTORE_PASSWORD:password}
    keystore-type: PKCS12